version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      # Volume db_data to persist database data outside of container.
      # When the container is deleted, the data still exists
      - db_data:/var/lib/postgresql/data
      # Host mount for one-time initialization.
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      # Map to other than default 5432 on host in case Postgres is also running natively on host.
      - "5433:5432"
  web:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_PORT: 5432
      DATABASE_HOST: db

volumes:
  # define volumn to keep existing Data and assign it above
  db_data:
